#!/bin/sh
 
# Computer Name Remediation Based on Active Directory Object
 
# name: script_setSharingNameAD.sh
# author: matt.lee@darkstarintegrations.com
# authorized user: matthew.lee@barclayscapital.com
 
# Read Active Directory Object Bound
adObject=`dsconfigad -show | awk '/Computer Account/{print $NF}' | tr '[a-z]' '[A-Z]' | sed s/.$//`
# Uncomment To Test Command
# echo $adObject
 
# Read Local Computer Name
sharingName=`scutil --get ComputerName`
# Uncomment To Test Command
# echo $sharingName
 
# Set Computer Name to Active Directory Object Name
setSharingName=`scutil --set ComputerName $adObject`
# Uncomment To Test Command
# echo #sharingName
 
# Verify Sharing Name and Change if Needed
if [ $adObject != $sharingName ] ; then
$setSharingName
fi
