#!/bin/bash

# NAME: Set Localhost
# AUTHOR: matt.lee@zimperium.com
# VERSION: 1.0.0
# DATE: 03/27/2018

# Fetching Serial Number
serialNumber=`system_profiler SPHardwareDataType | awk '/Serial/ {print $4}'`

# Setting Localhost to Serial Number
scutil --set LocalHostName $serialNumber$domain
