#!/bin/bash

# NAME: Set Computer Name
# AUTHOR: matt.lee@zimperium.com
# VERSION: 1.0.0
# DATE: 03/27/2018

# Fetching Serial Number
serialNumber=`system_profiler SPHardwareDataType | awk '/Serial/ {print $4}'`

 # Setting Computer Sharing Name to Serial Number
scutil --set ComputerName $serialNumber
